#[path = "apikey_create.rs"]
pub(crate) mod create;
#[path = "apikey_delete.rs"]
pub(crate) mod delete;
#[path = "apikey_disable.rs"]
pub(crate) mod disable;
#[path = "apikey_enable.rs"]
pub(crate) mod enable;
#[path = "apikey_list.rs"]
pub(crate) mod list;
#[path = "apikey_models.rs"]
pub(crate) mod models;
#[path = "apikey_profile.rs"]
pub(crate) mod profile;
#[path = "apikey_read_secret.rs"]
pub(crate) mod read_secret;
#[path = "apikey_service_tier.rs"]
pub(crate) mod service_tier;
#[path = "apikey_update_model.rs"]
pub(crate) mod update_model;
#[path = "apikey_usage_stats.rs"]
pub(crate) mod usage_stats;
